"""empty message

Revision ID: cc17ef7f44f5
Revises: 73bb0ccd03c5
Create Date: 2023-04-25 15:24:34.094275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc17ef7f44f5'
down_revision = '73bb0ccd03c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_staff')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_staff', sa.BOOLEAN(), nullable=False))
    # ### end Alembic commands ###
