"""empty message

Revision ID: d585938b2585
Revises: 5de3153bbe51
Create Date: 2023-05-03 22:31:24.338316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd585938b2585'
down_revision = '5de3153bbe51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_staff', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_staff')
    # ### end Alembic commands ###
